Update watchdog

diff --git a/watchdog b/watchdog
--- a/watchdog
+++ b/watchdog
@@ -232,7 +232,7 @@ lookForCMD="$executable"
                 if [ "$nl" == "0" ]; then
                 currentDir3=$(pwd)
                 cd /home/$USER/$longPackID/serverfiles/
-        tmux new-session -s $shortPackID "$executable" 2>/dev/null
+        tmux new-session -s $shortPackID "$executable" 2>/dev/null || echo "[INFO] Session start failed"
         dated=$(date)
                 cd $currentDir3
                 sleep 0.2
