Update watchdog

diff --git a/watchdog b/watchdog
--- a/watchdog
+++ b/watchdog
@@ -673,8 +673,15 @@ case "$1" in
         "stop"|"-st"|"shutdown")
                 unset act; act="shutdown"; MCManager
                 ;;
+        "-v"|"listvars")
+                cat vars.dog
+                ;;
+        "folder")
+                exit 0
+                ;;
         
-         *)     echo "[ERROR] Unknown command or no command specified "; echo ""; showHelp; exit 1
+         *)     
+                echo "[ERROR] Unknown command or no command specified "; echo ""; showHelp; exit 1
                 ;;
 esac
 
